import '../styles/globals.css'
import { Inter } from "next/font/google";
import Authprovider from './component/Authprovider/page';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}){

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Authprovider>
            {children}
          </Authprovider>
        </div>
      </body>
    </html>
  );
}
